# Generated by Django 6.0.6 on 2026-06-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_badge_product_original_price_product_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('charger', 'Charger'), ('case', 'Case & Cover'), ('earphone', 'Earphone'), ('smartwatch', 'Smart Watch'), ('powerbank', 'Power Bank'), ('accessory', 'Accessory')], max_length=50),
        ),
    ]
