# Generated by Django 6.0.6 on 2026-06-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_category_product_brand_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Mobiles', max_length=100),
            preserve_default=False,
        ),
    ]
