# Generated by Django 6.0.6 on 2026-06-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobiles', 'Mobiles'), ('chargers', 'Chargers'), ('cases', 'Cases & Covers'), ('earphones', 'Earphones'), ('smartwatches', 'Smart Watches'), ('powerbanks', 'Power Banks'), ('accessories', 'Accessories')], max_length=50),
        ),
    ]
